### ISSUE TITLE
SLAM odometry crashes in field tests

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/RustBot#11]
Here is a print screen of the error.

![slam](https://cloud.githubusercontent.com/assets/11350998/21054760/cec66240-be26-11e6-8ff1-bfd4a3b50c0c.png)

**Comment by harcadya** [comment]
O mesmo issue aparece em:
https://github.com/introlab/rtabmap_ros/issues/93

Parece que as imagens não chegam ao RTABMAP sincronizadas. Tinha discutido essa questão na quarta (7 Dez.).
Quanto a esse erro, tinhas reportado num email que: ".... Estava a funcionar online, 3Hz. Tem o problema de crashar por vezes (estimativa 1 vez a cada 3 minutos).". A possibilidade da sua ocorrência deve estar ligada ao passar do tempo (o sistema deve estar a entrar em unsync).

Experimenta colocar no launch do RTABMAP:


node pkg="rtabmap_ros" type="stereo_odometry" name="stereo_odometry" output="screen"
 ...
param name="approx_sync" type="bool" value="**true**"/

**Comment by miguelriemoliveira** [comment]
For now we are using viso2 with better results.
